config/routes.rb
Rails.application.routes.draw do
  get 'hello', to:'hello#index'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # Method get /about route
  get "about", to: "about#about", as: :about
  root to: "main#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  delete "logout", to: "sessions#destroy"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "accounts", to: "accounts#show"
  delete "accounts/:id", to: "accounts#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
# email:string
# password_digest:string
# password:string vitural
# password_confirmation:string vitural
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Invalid email'}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    def show
        @accounts = User.all
    end

    def destroy
        @account = User.find(params[:id].to_i)
        @account.destroy
        @posts = Post.where(user: params[:id].to_s)
        unless @posts.nil?
            @posts.each do |post|
                post.destroy
            end
        end
        redirect_to accounts_path, notice: "Account was successfully destroyed."
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: 'You must be logged in' if Current.user.nil?
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # flash.now[:notice] = "Welcome to the site!"
    # flash.now[:alert] = "Invalid username or password!"
  end
    
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            # Send mail to the user
            PasswordMailer.with(user: @user).reset.deliver_now
            flash[:success] = "Email sent with password reset instructions"
            redirect_to root_path, notice: 'Email sent with password reset instructions'
        else
            redirect_to root_path, notice: 'Email not found.'
        end
    end

    def edit
        @user = User.find_signed(params[:token], purpose: "password_reset")
        # binding.irb
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, notice: "Invalid or expired password reset token"
    end

    def update
        @user = User.find_signed(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Password has been reset"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated successfully"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_user_logged_in!, only: %i[ create update destroy new edit]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        # format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :poster, :tag).merge(user: Current.user.id)
    end
end


# Thêm phân quyền -> xóa user là xóa post, người tạo post mới được thao tác với post

# Key: has many, belong to -> cách tạo post

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to sign_in_path, notice: 'User was successfully created.'
        else
            flash[:alert] = 'User was not created.'
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: 'Logged in!'
        else
            flash.now[:alert] = 'Invalid username or password!'
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: 'Logged out!'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/about.html.erb
<div class="about-section">
  <h1>About Page</h1>
  <p>About page write with erb file Ruby</p>
</div>

<h2 style="text-align:center">Meo</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img id='dora' src="https://znews-photo.zadn.vn/w660/Uploaded/mdf_vsxrlu/2021_01_22/meo_3_2.jpg" alt="Meomeo">
      <div class="container">
        <h2>Meo meo</h2>
        <p class="title">CEO & Founder</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>meomeo@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<%= link_to 'Go to sign in', sign_in_path , class:"btn btn-success"%>
<hr>
<% @accounts.each do |account| %>
	<div class="list-group">
		<a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
			<div class="d-flex w-100 justify-content-between">
				<h5 class="mb-1">User ID: <%= account.id %></h5>
			</div>
			<p class="mb-1">Email: <%= account.email %></p>
		</a>
		<% unless Current.user.nil?  %>
			<% if account.id != Current.user.id %>
				<%= button_to "Remove user", {controller: :accounts, action: :destroy, id: account.id}, method: :delete, class:'btn btn-danger' %>
			<% end %>
		<% end %>
	</div>
	<br>
<% end %>

app/views/hello/index.html.erb
<h1>Hello#index</h1>
<p>Find me in app/views/hello/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>ScheduledTweets</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

	</head>
	<header>
		<%= render partial: "shared/navbar" %>
	</header>
	<body>
		<div class="container">
            <%= render partial: "shared/flash" %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
	<h1>Maintainer</h1>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
	<% if form.object.errors.any? %>
		<div class="alert alert-danger">
			<% form.object.errors.full_messages.each do |message| %>
				<div><%= message %></div>
			<% end %>
		</div>
	<% end %>
	<div class='mb-3'>
		<%= form.label :password %>
		<%= form.password_field :password, class: "form-control", placeholder: "Password"%>
	</div>
	<div class='mb-3'>
		<%= form.label :password_confirmation %>
		<%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password"%>
	</div>
	<div class="mb-3">
		<%= form.submit "Reset Password", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password</h1>
<%= form_with url: password_reset_path do |form| %>
	<div class="mb-3">
		<%= form.label :email, "Email" %>
		<%= form.email_field :email, class: "form-control", placeholder: "Email" %>
	</div>
	<div class="mb-3">
		<%= form.submit "Reset Password", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div  class="form-group">
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :poster, style: "display: block" %>
    <%= form.text_field :poster, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :tag, style: "display: block" %>
    <%= form.text_field :tag, class: "form-control"%>
  </div>
  <br>
  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
	<div class="card" style="width: 18rem;">
		<div class="card-body">
			<h5 class="card-title">Poster: <%= post.poster %></h5>
			<h6 class="card-subtitle mb-2 text-muted">Tag: <%= post.tag %></h6>
			<p class="card-text">Content: <%= post.content %></p>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post, class: "btn btn-success" %> |
  <%= link_to "Back to posts", posts_path, class: "btn btn-light"%>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Posts</h1>
<div id="posts">
	<% @posts.each do |post| %>
		<div>
			<div style="margin-left: 10px;">
				<%= render post %>
				<p style='margin-left: 10px'>
					<%= link_to "Show this post", post %>
				</p>
			</div>
		</div>
	<% end %>
</div>
<%= link_to "New post", new_post_path , class:"btn btn-primary"%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @post %>
<div>
	<% unless Current.user.nil? %>
		<% if @post.user.to_i == Current.user.id %>
			<%= link_to "Edit this post", edit_post_path(@post) , class:'btn btn-success' %>
			<%= button_to "Destroy this post", post_path, method: :delete, class:'btn btn-danger' %>
		<% end %>
	<% end %>
	<hr>
	<%= link_to "Back to posts", posts_path, class:'btn btn-light' %>
</div>

app/views/shared/_flash.html.erb
<% if flash.any? %>
	<% flash.each do |type, value| %>
		<div id='flash-msg' class="alert alert-<%= type == 'notice' ? 'success' : 'danger' %> mt-4 close-div">
			<%= value %>
		</div>
	<% end %>
<% end %>
<script type="text/javascript">
	$(document).ready(function(){
		$('#flash-msg').delay(3000).slideUp(300);
	});
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
		<%= link_to "Home", root_path, class: "navbar-brand" %>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<%= link_to "About", about_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Users", accounts_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Posts", posts_path, class: "nav-link" %>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if Current.user %>
					<li class="nav-item">
						<%= button_to "Sign out", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
					</li>
					<li class="nav-item">
						<%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
					</li>
				<% else %>
					<li class="nav-item">
						<%= link_to "Sign in", sign_in_path, method: :post, class: "nav-link" %>
					</li>
					<li class="nav-item">
						<%= link_to "Sign up", sign_up_path, class: "nav-link" %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>